from pathlib import Path

import joblib
import pandas as pd
from flask import Flask, render_template, request

app = Flask(__name__)

PROJECT_ROOT = Path(__file__).resolve().parent
MODELS_DIR = PROJECT_ROOT / "Models"
OUTPUTS_DIR = PROJECT_ROOT / "Outputs"
DATASET_DIR = PROJECT_ROOT / "Dataset"


def _find_dataset_file(new_name, legacy_name):
    """Find a prepared file without changing the existing preprocessing."""

    new_path = DATASET_DIR / new_name
    legacy_path = DATASET_DIR / legacy_name
    if new_path.exists():
        return new_path
    if legacy_path.exists():
        return legacy_path
    return None


def load_model_results():
    """Read the real model-comparison CSV generated by train_models.py."""

    comparison_path = OUTPUTS_DIR / "Model_Comparison" / "model_comparison.csv"
    if not comparison_path.exists():
        return [], None

    comparison = pd.read_csv(comparison_path)
    rows = comparison.to_dict(orient="records")
    best_name = str(rows[0]["Model"]) if rows else None
    return rows, best_name


def load_prediction_data():
    """Load the actual prepared test features and targets for safe demo prediction."""

    x_path = _find_dataset_file("06_split_X_test.csv", "X_test.csv")
    y_path = _find_dataset_file("06_split_y_test.csv", "y_test.csv")
    if x_path is None or y_path is None:
        return None, None
    return pd.read_csv(x_path), pd.read_csv(y_path)["loss"]


def model_is_ready():
    return (MODELS_DIR / "best_model.pkl").exists() and bool(load_model_results()[0])

@app.route("/")
@app.route("/index")
def index():
    return render_template("index.html")

@app.route("/about")
def about():
    return render_template("about.html")

@app.route("/dataset")
def dataset():
    return render_template("dataset.html")

@app.route("/preprocessing")
def preprocessing():
    return render_template("preprocessing.html")

@app.route("/visualization")
def visualization():
    return render_template("visualization.html")

@app.route("/models")
def models():
    model_rows, best_name = load_model_results()
    return render_template(
        "models.html",
        model_rows=model_rows,
        best_name=best_name,
        model_ready=bool(model_rows),
    )

@app.route("/prediction", methods=["GET", "POST"])
def prediction():
    model_rows, best_name = load_model_results()
    result = None
    error = None
    x_test, y_test = load_prediction_data()

    if request.method == "POST":
        if not model_is_ready() or x_test is None or y_test is None:
            error = "Train the regression models first. The saved best model or test data is unavailable."
        else:
            try:
                row_index = int(request.form.get("row_index", ""))
                if row_index < 0 or row_index >= len(x_test):
                    raise ValueError(f"Choose a test-row number from 0 to {len(x_test) - 1}.")

                model = joblib.load(MODELS_DIR / "best_model.pkl")
                row = x_test.iloc[[row_index]]
                expected_columns = list(getattr(model, "feature_names_in_", row.columns))
                if list(row.columns) != expected_columns:
                    raise ValueError("The selected test row does not match the trained model feature structure.")

                predicted_loss = float(model.predict(row)[0])
                result = {
                    "row_index": row_index,
                    "predicted_loss": predicted_loss,
                    "actual_loss": float(y_test.iloc[row_index]),
                    "feature_count": row.shape[1],
                }
            except (TypeError, ValueError) as exc:
                error = str(exc)
            except Exception as exc:  # pragma: no cover - protects the web page from model-load errors
                error = f"Prediction could not be completed: {exc}"

    feature_count = int(x_test.shape[1]) if x_test is not None else 0
    return render_template(
        "prediction.html",
        model_rows=model_rows,
        best_name=best_name,
        model_ready=model_is_ready(),
        test_row_count=len(x_test) if x_test is not None else 0,
        feature_count=feature_count,
        result=result,
        error=error,
    )

@app.route("/dashboard")
def dashboard():
    model_rows, best_name = load_model_results()
    best_metrics = model_rows[0] if model_rows else None
    return render_template(
        "dashboard.html",
        model_rows=model_rows,
        best_name=best_name,
        best_metrics=best_metrics,
        model_ready=bool(model_rows),
    )

@app.route("/reports")
def reports():
    model_rows, best_name = load_model_results()
    best_metrics = model_rows[0] if model_rows else None
    return render_template(
        "reports.html",
        model_rows=model_rows,
        best_name=best_name,
        best_metrics=best_metrics,
        model_ready=bool(model_rows),
    )

@app.route("/contact")
def contact():
    return render_template("contact.html")

if __name__ == "__main__":
    app.run(debug=True, port=5000)
